baseurl = "https://lapingvino.github.io/esperanto-kurso-hugo"
canonifyurls = true
copyright = "© 2016 Joop Kiefte kaj aliaj - enhavo havebla sub AGPL, vidu en GitHub"
googleAnalytics = "Your Tracking Id"
paginate = 10
theme = "amp"
title = "lerni Esperanton sen uzi alian lingvon ol Esperanto"
[[menu.header]]
name = "Pri ĉi tiu retejo"
url = "/pri/"
weight = 2
[[menu.header]]
name = "GitHub"
url = "https://github.com/esperanto/esperanto-kurso.net"
weight = 1
